### PR TITLE
Webpack Uglify Compatibility Fix

### LINKED ISSUE #13: Console error after Webpack uglify
Hi,
I'm trying to include basicScroll in a Roots/[Sage](https://github.com/roots/sage) project and I'm getting a console error after building my assets for production.

```
TypeError: l is not a function. (In 'l(t,c,f,h)', 'l' is 4)
```

I'm not the most webpack savvy user, so my troubleshooting is limited. The library works great when the assets aren't uglified, but throw the above error in the browser console when the webpack bundle is uglified.

I've tried separating basicScroll into its own separate script file (still uglified) with the same result. I've also tried a fresh copy of Sage with no other (non-default) dependencies, also with the same result.

I'm happy to try any more troubleshooting steps you can suggest. Thank you for your time and for this awesome library.

### PR DESCRIPTION
**Pull request by aaronwaldon**
Added semicolons to fix the unterminated statements that were preventing the module from working with Webpack uglify. Fixes #13.

### CODE REVIEW

**Comment by electerious** [comment]
I wonder why this causes an error. Non of those semicolons are actually required. It would be great if someone could open an issue on the tool causing the issues (uglify?).

**Comment by aaronwaldon** [comment]
JavaScript can perform automatic semicolon insertion if they are accidentally (or intentionally) omitted, but it does actually need them to separate statements. Although the live parsing engine can usually figure out where to add them, barring a few pitfalls, it makes it hard for some other tools to guess what was intended. For maximum compatibility, it can be useful to add the semicolons where they are expected. Some IDEs (like Jetbrain's Webstorm and other products) also highlight the places the semicolons are needed (where automatic semicolon insertion would add them).

If you don't want to add them in, that's okay. I can add them in locally to use your excellent library with webpack as needed. I appreciate your great library and your taking the time to share and maintain it!

**Comment by electerious** [comment]
The UglifyjsWebpackPlugin is based on uglify-es which still has a lot of reported bugs: https://github.com/mishoo/UglifyJS2/issues

I've opened an issue so they have a chance to fix it before we work around it.

**Comment by fabiosantoscode** [comment]
If you're using `yarn`, you can update the unmaintained `uglify-es` to the new maintained fork `terser` by following these instructions: https://github.com/fabiosantoscode/terser/#replacing-uglify-es-with-terser-in-a-project-using-yarn

Does that work?

**Comment by aaronwaldon** [comment]
I believe the issue was caused by using the webpack.optimize.UglifyJsPlugin in Webpack 3. I have since migrated to Webpack 4 and switched to the TerserPlugin, and everything seems to be working as expected. Thank you for the help and guidance!

**Pull request closed without merging**
